version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /imgs
  static_dir: imgs

- url: /.*
  script: guestbook.app
libraries:
- name: pycrypto
  version: "2.6"
- name: webapp2
  version: "latest"
- name: jinja2
  version: "latest"
